spring:
  datasource:
    #    url: jdbc:mysql://i6a302.p.ssafy.io:3306/-------?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/a302db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: a302pinako
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver