spring:
  profiles:
    include: jpa,database,jwt,server,springdoc,mail

  devtools:
    restart:
      enabled: true

  messages:
    basename: messages,errors

#  task:
#    scheduling:
#      pool:
#        size: 3

logging:
  level:
    com.ssafy.bjbj: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug