spring:
  profiles:
    include: jpa,database,openapi
  task:
    scheduling:
      pool:
        size: 10


logging:
  level:
    com.ssafy.bjbj: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug

#
#server:
#  port: 8081